baseURL = 'https://lentsu.github.io/'
languageCode = 'en-us'
title = 'Lenni Toikkanen'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Portfolio Website"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Footer settings
showFooter = true
footerContent = "© Lenni Toikkanen 2025"

homeIntroTitle = 'Hello!'
homeIntroContent = """
I'm Lenni, a M.Sc. (tech) electronics and nanoengineering student at Aalto University, specializing in Microelectronic circuit design. I have a strong background in programming and a passion for low-level. Welcome to my engineering portfolio!
"""
homePicture = "/profile.jpg"

# Collection to display on home
homeCollectionTitle = 'Projects'
homeCollection = 'projects'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "~"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/lenni-toikkanen/"

[[params.social]]
name = "github"
url = "https://github.com/Lentsu"

[[params.social]]
name = "gmail"
url = "mailto:mail@lennitoikkanen.fi"

# Main menu pages
[[params.menu]]
name = "Home"
url = "/"

[[params.menu]]
name = "Projects"
url = "/projects"

[[params.menu]]
name = "Experience"
url = "/experience"

[[params.menu]]
name = "Education"
url = "/education"

[[params.menu]]
name = "Contact"
url = "/contact"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
